INSERT INTO users (name, age) VALUES ("Kameron", 27);
INSERT INTO users (name, age) VALUES ("Grace", 25);
INSERT INTO users (name, age) VALUES ("Opal", 41);
INSERT INTO users (name, age) VALUES ("Blake", 26);
INSERT INTO users (name, age) VALUES ("Kristin", 25);
INSERT INTO users (name, age) VALUES ("Kali", 26);
INSERT INTO users (name, age) VALUES ("Linda", 55);
INSERT INTO users (name, age) VALUES ("Keith", 54);
INSERT INTO users (name, age) VALUES ("Olivia", 28);
INSERT INTO users (name, age) VALUES ("John", 30);
INSERT INTO users (name, age) VALUES ("Ashley", 65);
INSERT INTO users (name, age) VALUES ("Charles", 45);
INSERT INTO users (name, age) VALUES ("Lorin", 41);
INSERT INTO users (name, age) VALUES ("Jesus", 100);
INSERT INTO users (name, age) VALUES ("Jenny", 34);
INSERT INTO users (name, age) VALUES ("Janette", 58);
INSERT INTO users (name, age) VALUES ("Melody", 53);
INSERT INTO users (name, age) VALUES ("Craig", 35);
INSERT INTO users (name, age) VALUES ("Tyler", 27);
INSERT INTO users (name, age) VALUES ("Vicki", 50);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project A", "Business", 1000, "01/03/2011", "05/04/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project B", "Recreational", 2000, "07/30/2000", "10/21/2050");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project C", "Other", 10000, "06/02/1993", "06/02/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project D", "Business", 100000, "08/21/2001", "09/25/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project E", "Other", 1000, "10/30/1990", "02/21/2035");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project F", "Other", 20000, "10/01/2001", "10/01/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project G", "Recreational", 10200, "11/20/2000", "12/25/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project H", "Recreational", 50000, "01/01/1999", "01/19/2022");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project I", "Other", 510, "03/28/1992", "06/09/2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project J", "Other", 10, "04/01/2016", "05/20/2019");

INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (450, 19, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 19, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (375, 16, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (270, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 10, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (700, 19, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 20, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 13, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (299, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 1, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 7, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 9, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (99, 8, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (650, 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (550, 15, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 11, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 12, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 7, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 8, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 16, 4);